apiVersion: v2
name: umbrella-chart
description: Umbrella chart to deploy Bitnami nginx
type: application
version: 0.1.0
dependencies:
  - name: nginx
    version: 21.0.6
    repository: oci://845258155985.dkr.ecr.eu-central-1.amazonaws.com/bitnamicharts
appVersion: "1.0"
