apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-helm-direct
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    helm:
      valuesObject:
        service:
          type: ClusterIP
    chart: nginx
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 21.0.8
  destination:
    server: https://kubernetes.default.svc
    namespace: direct
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
