apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-helm-direct-private
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    helm:
      valuesObject:
        service:
          type: ClusterIP
    chart: nginx
    repoURL: 845258155985.dkr.ecr.eu-central-1.amazonaws.com/bitnamicharts
    targetRevision: 21.0.6
  destination:
    server: https://kubernetes.default.svc
    namespace: direct-private
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
