apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-helm-umbrella
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    path: 001-argo-helm/umbrella-chart-private
    repoURL: https://github.com/SimonKO9/blog-demos-k8s.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: umbrella-private
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
